### ISSUE TITLE
Text field should add class 'textarea'

### ISSUE THREAD

**Issue by nickhammond** [JuanVqz/simple_form-theme#13]
Thanks for making this!

Given a view:

```
<%= simple_form_for company do |form| %>
  <%= form.input :terms_and_conditions %>
<% end %> 
```

It renders as:
```
<textarea class="input text optional" name="company[terms_and_conditions]" id="company_terms_and_conditions" spellcheck="false"></textarea>
```

Bulma has a `textarea` class for that field type though https://bulma.io/documentation/form/textarea/ instead of `text`.

**Comment by JuanVqz** [comment]
@nickhammond the text field should include the textarea class, make sure to use the latest release, thanks for reporting it, and happy coding!
